# Generated by Django 3.0.4 on 2020-03-12 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.FloatField(default=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='weight_goal',
            field=models.FloatField(default=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
